services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: litellm
    ports:
      - "5432:5432"
    restart: always
  litellm:
    image: ghcr.io/berriai/litellm-database:main-v1.35.10
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
      - UI_USERNAME=${UI_USERNAME}
      - UI_PASSWORD=${UI_PASSWORD}
    ports:
      - "4000:4000"
    restart: always
    command: --config /app/litellm.yml --num_workers 8
    depends_on:
      - postgres

# docker compose up -d --build postgres
# docker compose up -d --build litellm